// <copyright file="Server.cs" company="APIMatic">
// MultiAuthSample.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>

namespace MultiAuthSample.Standard
{
    /// <summary>
    /// Available servers.
    /// </summary>
    public enum Server
    {
        /// <summary>
        /// Default.
        /// </summary>
        Default,

        /// <summary>
        /// Auth.
        /// </summary>
        Auth,
    }
}
