// <copyright file="OAuthScopeOAuthACGEnum.cs" company="APIMatic">
// MultiAuthSample.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;

namespace MultiAuthSample.Standard.Models
{
    /// <summary>
    /// OAuthScopeOAuthACGEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum OAuthScopeOAuthACGEnum
    {
        /// <summary>
        ///Read request for files
        /// ReadScope.
        /// </summary>
        [EnumMember(Value = "file_requests.read")]
        ReadScope
    }

    internal static class OAuthScopeOAuthACGEnumExtensions
    {
        internal static string GetValues(this IEnumerable<OAuthScopeOAuthACGEnum> values) => values != null
            ? string.Join(" ", values.Select(s => s.GetValue()).Where(s => !string.IsNullOrEmpty(s)).ToArray())
            : null;

        private static string GetValue(this Enum value) =>
            value.GetType()
                .GetTypeInfo()
                .DeclaredMembers
                .SingleOrDefault(x => x.Name == value.ToString())
                ?.GetCustomAttribute<EnumMemberAttribute>(false)
                ?.Value;
    }
}