// <copyright file="ServiceStatus.cs" company="APIMatic">
// MultiAuthSample.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace MultiAuthSample.Standard.Models
{
    /// <summary>
    /// ServiceStatus.
    /// </summary>
    public class ServiceStatus : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceStatus"/> class.
        /// </summary>
        public ServiceStatus()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceStatus"/> class.
        /// </summary>
        /// <param name="status">status.</param>
        /// <param name="app">app.</param>
        /// <param name="moto">moto.</param>
        /// <param name="notes">notes.</param>
        /// <param name="users">users.</param>
        /// <param name="time">time.</param>
        /// <param name="os">os.</param>
        /// <param name="phpVersion">php_version.</param>
        public ServiceStatus(
            string status,
            string app = "",
            string moto = "",
            int? notes = null,
            int? users = null,
            string time = "",
            string os = "",
            string phpVersion = "")
        {
            this.App = app;
            this.Moto = moto;
            this.Notes = notes;
            this.Users = users;
            this.Time = time;
            this.Os = os;
            this.PhpVersion = phpVersion;
            this.Status = status;
        }

        /// <summary>
        /// Gets or sets App.
        /// </summary>
        [JsonProperty("app", NullValueHandling = NullValueHandling.Ignore)]
        public string App { get; set; }

        /// <summary>
        /// Gets or sets Moto.
        /// </summary>
        [JsonProperty("moto", NullValueHandling = NullValueHandling.Ignore)]
        public string Moto { get; set; }

        /// <summary>
        /// Gets or sets Notes.
        /// </summary>
        [JsonProperty("notes", NullValueHandling = NullValueHandling.Ignore)]
        public int? Notes { get; set; }

        /// <summary>
        /// Gets or sets Users.
        /// </summary>
        [JsonProperty("users", NullValueHandling = NullValueHandling.Ignore)]
        public int? Users { get; set; }

        /// <summary>
        /// Gets or sets Time.
        /// </summary>
        [JsonProperty("time", NullValueHandling = NullValueHandling.Ignore)]
        public string Time { get; set; }

        /// <summary>
        /// Gets or sets Os.
        /// </summary>
        [JsonProperty("os", NullValueHandling = NullValueHandling.Ignore)]
        public string Os { get; set; }

        /// <summary>
        /// Gets or sets PhpVersion.
        /// </summary>
        [JsonProperty("php_version", NullValueHandling = NullValueHandling.Ignore)]
        public string PhpVersion { get; set; }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ServiceStatus : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ServiceStatus other &&
                (this.App == null && other.App == null ||
                 this.App?.Equals(other.App) == true) &&
                (this.Moto == null && other.Moto == null ||
                 this.Moto?.Equals(other.Moto) == true) &&
                (this.Notes == null && other.Notes == null ||
                 this.Notes?.Equals(other.Notes) == true) &&
                (this.Users == null && other.Users == null ||
                 this.Users?.Equals(other.Users) == true) &&
                (this.Time == null && other.Time == null ||
                 this.Time?.Equals(other.Time) == true) &&
                (this.Os == null && other.Os == null ||
                 this.Os?.Equals(other.Os) == true) &&
                (this.PhpVersion == null && other.PhpVersion == null ||
                 this.PhpVersion?.Equals(other.PhpVersion) == true) &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"App = {this.App ?? "null"}");
            toStringOutput.Add($"Moto = {this.Moto ?? "null"}");
            toStringOutput.Add($"Notes = {(this.Notes == null ? "null" : this.Notes.ToString())}");
            toStringOutput.Add($"Users = {(this.Users == null ? "null" : this.Users.ToString())}");
            toStringOutput.Add($"Time = {this.Time ?? "null"}");
            toStringOutput.Add($"Os = {this.Os ?? "null"}");
            toStringOutput.Add($"PhpVersion = {this.PhpVersion ?? "null"}");
            toStringOutput.Add($"Status = {this.Status ?? "null"}");

            base.ToString(toStringOutput);
        }
    }
}