// <copyright file="SuiteCodeEnum.cs" company="APIMatic">
// MultiAuthSample.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;

namespace MultiAuthSample.Standard.Models
{
    /// <summary>
    /// SuiteCodeEnum.
    /// </summary>

    [JsonConverter(typeof(NumberEnumConverter))]
    public enum SuiteCodeEnum
    {
        /// <summary>
        /// Hearts.
        /// </summary>
        Hearts = 1,

        /// <summary>
        /// Spades.
        /// </summary>
        Spades = 2,

        /// <summary>
        /// Clubs.
        /// </summary>
        Clubs = 3,

        /// <summary>
        /// Diamonds.
        /// </summary>
        Diamonds = 4
    }
}