// <copyright file="ApiHelper.cs" company="APIMatic">
// MultiAuthSample.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities;

namespace MultiAuthSample.Standard.Utilities
{
    /// <summary>
    /// ApiHelper class contains a bunch of helper methods.
    /// </summary>
    public class ApiHelper : CoreHelper { }
}
