// <copyright file="ControllerTestBase.cs" company="APIMatic">
// MultiAuthSample.Tests
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MultiAuthSample.Standard;
using MultiAuthSample.Standard.Authentication;
using MultiAuthSample.Standard.Exceptions;
using MultiAuthSample.Standard.Http.Client;
using MultiAuthSample.Standard.Models;
using NUnit.Framework;

namespace MultiAuthSample.Tests
{
    /// <summary>
    /// ControllerTestBase Class.
    /// </summary>
    [TestFixture]
    public class ControllerTestBase
    {
        /// <summary>
        /// Assert precision.
        /// </summary>
        protected const double AssertPrecision = 0.1;

        /// <summary>
        /// Gets HttpCallBackHandler.
        /// </summary>
        internal HttpCallback HttpCallBack { get; private set; } = new HttpCallback();

        /// <summary>
        /// Gets MultiAuthSampleClient Client.
        /// </summary>
        protected MultiAuthSampleClient Client { get; private set; }

        /// <summary>
        /// Set up the client.
        /// </summary>
        [OneTimeSetUp]
        public void SetUp()
        {
            MultiAuthSampleClient config = MultiAuthSampleClient.CreateFromEnvironment();
            this.Client = config.ToBuilder()
                .HttpCallback(HttpCallBack)
                .BasicAuthCredentials(new BasicAuthModel.Builder("Zeeshan", "bhai_99").Build())
                .ApiKeyCredentials(new ApiKeyModel.Builder("asdqwaxr2gSdhasWSDbdAgdA637sdAhde7Adysi23", "api-key").Build())
                .ApiHeaderCredentials(new ApiHeaderModel.Builder("Qaws2W233WedeRe4T56G6Vref2", "api-key").Build())
                .OAuthCCGCredentials(new OAuthCCGModel.Builder("23", "tQNSqQlXBIwZcY9auoujQ57ckDcoh3t8UPbBRkSF").Build())
                .OAuthACGCredentials(new OAuthACGModel.Builder("24", "Y9auoujQ57ckDtQNSqQlXBIwZccoh3t8UPbBRkSF", "x").Build())
                .OAuthROPCGCredentials(new OAuthROPCGModel.Builder("25", "ckDcoh3t8UPbBRkSFtQNSqQlXBIwZcY9auoujQ57", "apimatic", "api-d604257e42-matic").Build())
                .OAuthBearerTokenCredentials(new OAuthBearerTokenModel.Builder("0b79bab50daca910b000d4f1a2b675d604257e42").Build())
                .AccessToken2("azHmdOe09EdchxeWsdnplkQbv76sJH")
                .Build();


            try
            {
                this.Client = this.Client.ToBuilder().OAuthACGCredentials(Client.OAuthACGModel.ToBuilder()
                    .OAuthToken(this.Client.OAuthACGCredentials.FetchToken("910b000d4f")).Build())
                    .Build();
            }
            catch (ApiException) 
            {
                // TODO Auto-generated catch block;
            }

            try
            {
                this.Client = this.Client.ToBuilder().OAuthROPCGCredentials(Client.OAuthROPCGModel.ToBuilder()
                    .OAuthToken(this.Client.OAuthROPCGCredentials.FetchToken()).Build())
                    .Build();
            }
            catch (ApiException) 
            {
                // TODO Auto-generated catch block;
            }
        }
    }
}