// <copyright file="ICustomAuthCredentials.cs" company="APIMatic">
// MultiAuthSample.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>

namespace MultiAuthSample.Standard.Authentication
{
    /// <summary>
    /// Authentication configuration interface for CustomAuth.
    /// </summary>
    public interface ICustomAuthCredentials
    {
        /// <summary>
        ///  Returns true if credentials matched.
        /// </summary>
        /// <returns>True if credentials matched.</returns>
        bool Equals();
    }
}