// <copyright file="OAuthBearerTokenManager.cs" company="APIMatic">
// MultiAuthSample.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using APIMatic.Core.Authentication;

namespace MultiAuthSample.Standard.Authentication
{
    /// <summary>
    /// OAuthBearerTokenManager.
    /// </summary>
    internal class OAuthBearerTokenManager : AuthManager, IOAuthBearerTokenCredentials
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthBearerTokenManager"/> class.
        /// </summary>
        /// <param name="oAuthBearerTokenModel">OAuthBearerTokenModel.</param>
        public OAuthBearerTokenManager(OAuthBearerTokenModel oAuthBearerTokenModel)
        {
            this.AccessToken = oAuthBearerTokenModel?.AccessToken;
            Parameters(paramBuilder => paramBuilder
                .Header(header => header.Setup("Authorization",
                    this.AccessToken == null ? null : $"Bearer {this.AccessToken}"
                ).Required()));
        }

        /// <summary>
        /// Gets string value for accessToken.
        /// </summary>
        public string AccessToken { get; }

        /// <summary>
        /// Check if credentials match.
        /// </summary>
        /// <param name="accessToken"> The string value for credentials.</param>
        /// <returns> True if credentials matched.</returns>
        public bool Equals(string accessToken)
        {
            return accessToken.Equals(this.AccessToken);
        }

    }

    public sealed class OAuthBearerTokenModel
    {
        internal OAuthBearerTokenModel()
        {
        }

        internal string AccessToken { get; set; }

        /// <summary>
        /// Creates an object of the OAuthBearerTokenModel using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            return new Builder(AccessToken);
        }

        /// <summary>
        /// Builder class for OAuthBearerTokenModel.
        /// </summary>
        public class Builder
        {
            private string accessToken;

            public Builder(string accessToken)
            {
                this.accessToken = accessToken ?? throw new ArgumentNullException(nameof(accessToken));
            }

            /// <summary>
            /// Sets AccessToken.
            /// </summary>
            /// <param name="accessToken">AccessToken.</param>
            /// <returns>Builder.</returns>
            public Builder AccessToken(string accessToken)
            {
                this.accessToken = accessToken ?? throw new ArgumentNullException(nameof(accessToken));
                return this;
            }

            /// <summary>
            /// Creates an object of the OAuthBearerTokenModel using the values provided for the builder.
            /// </summary>
            /// <returns>OAuthBearerTokenModel.</returns>
            public OAuthBearerTokenModel Build()
            {
                return new OAuthBearerTokenModel()
                {
                    AccessToken = this.accessToken
                };
            }
        }

        internal static OAuthBearerTokenModel FromOptions(OAuthBearerTokenModelOptions options)
        {
            var builder = new Builder(options.AccessToken);
            return builder.Build();
        }
    }

    public class OAuthBearerTokenModelOptions
    {
        public string AccessToken { get; set; }
    }
}